version: "3"
services:
  php:
    build:
      context: .
    expose:
      - "9000"
    volumes:
      - ./src:/var/www/html 

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 